[general]
import = ["~/.config/alacritty/themes/themes/dark_plus.toml"]

[font]
normal.family = "Cascadia Mono"
bold.family = "Cascadia Mono"
italic.family = "Cascadia Mono"
bold_italic.family = "Cascadia Mono"

size = 11.0
